//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiFrameworkProject1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public int Id { get; set; }
        public string path { get; set; }
        public string place { get; set; }
        public string type { get; set; }
        public int LinkMediaPersonId { get; set; }
    
        public virtual LinkMediaPerson LinkMediaPerson { get; set; }
    }
}
